### ISSUE TITLE
Error mining and Feeding

### ISSUE THREAD

**Issue by hengkyhks** [SFGamink/kuroroBOT#6]
![image](https://github.com/user-attachments/assets/b7bdfc4e-0e05-47e6-9aea-948639f34b38)

**Comment by SFGamink** [comment]
pm ke tele @ExoProKiKi

**Comment by Minecryp** [comment]
I also have the same problem.

**Comment by SFGamink** [comment]
> I also have the same problem.

Chat to tele @ExoProKiKi
